# Generated by Django 3.2.3 on 2021-06-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='cin',
            field=models.PositiveBigIntegerField(default=12345678),
        ),
        migrations.AddField(
            model_name='doctor',
            name='speciality',
            field=models.CharField(default='Psychiatry', max_length=20),
        ),
    ]
